### ISSUE TITLE
Add Options to memoize first style calculation after component mounted?

### ISSUE THREAD

**Issue by azaslavsky** [buildbreakdo/style-it#19]
I suppose this is a feature request that I'd like to get your opinion on.  I use the library to inject a static string of CSS styles, like so:

```jsx
import Style from 'style-it';
import styleSheet from './index.scss';

class MyComp extends React.Component {
  /* OTHER CLASS STUFF */
  render() {
    return Style.it(styleSheet, <div className="foobar">Some Content</div>);
  }
}
```

Since I'm passing a static style string, the stylesheet does not need to be rebuilt each time render is run, only the first time.  It would be nice it style.if (or the `<Style>` component) accepted a third options argument, with something like an `onlyGenerateOnce` parameter to indicate that the stylesheet never needs to be rebuilt after it is originally created.

**Comment by buildbreakdo** [comment]
@azaslavsky Yes -- this is a good idea! Believe the best approach is not to expand the API footprint and go ahead and handle this internally, CSS string passed in would be the key and scoped CSS string would be the value (memoize).

Potential issue could be if the object kept growing over a large period of time, thinking live data with props not marked as internal or document root. May be best to limit to last 10 or 100 (some arbitrary number). I'll think on it and try to have something up by Sunday, Monday night at the latest (India time). 

Have any additional thoughts, I'm all ears. Thanks for opening this!

**Comment by buildbreakdo** [comment]
@azaslavsky This is in, huge performance gain. Thanks so much for opening this! Opensource FTW 👍

**Comment by azaslavsky** [comment]
Wow, totally missed your first comment, or I woulda been happy to contribute!  Either way, this looks super solid, thanks a lot for the quick turnaround!
