### ISSUE TITLE
Style not generated when using classname composition

### ISSUE THREAD

**Issue by nicmosc** [buildbreakdo/style-it#28]
When using the reactive syntax and a composed classname to set the styles in a component, the Style it styles don't seem to be generated. Example:

```
<Style>
.${styles.toggler}:
   background: red;
}
.${styles.activeToggler} {
   background: blue;
}
</Style>
```
The first rule is correctly applied, but when the second classname is given to the element, nothing happens (the background is still red). The css for the components above has this pattern:

```
:local(.toggler) {
   some_css_rule: ...
}
:local(.activeToggler) {
   composes: toggler;
   some_other_css_rule: ...
}
```

Removing the line `composes: toggler` will make the `Style` css rules work.

For reference:
Style-it: 2.0.0
React: 16.4.1

**Comment by buildbreakdo** [comment]
Hi! Thanks for opening this, see a few typos. Example is missing the JSX embedded expression syntax, string template declaration, and the first rule is using a semicolon instead of an open brace.  

Working example is below:

```
class Intro extends React.Component {
  render() {
  	const styles = {
    	toggler: 'foo',
      activeToggler: 'bar'
    }
    
    return (
    	<div>
        <Style>
          {`
              .${styles.toggler} {
                background: red;
	      }
	      .${styles.activeToggler} {
                color: blue;
	      }
          `}
       </Style>
     
        <p className="intro foo bar">CSS-in-JS made simple -- just Style It</p>
      </div>
    );
  }
}

ReactDOM.render(
  <Intro />,
  document.getElementById('container')
);
```

See this live here: https://jsfiddle.net/8mjcqv6e/15/
