### ISSUE TITLE
problem with generate CSS style for child component

### ISSUE THREAD

**Issue by samankhademi** [buildbreakdo/style-it#29]
hello i want set Style to sub child but css not generate correctly
my code
```
    return Style.it(`.ant-table-tbody tr td {color: red}`,
        <div className='sample'>
          <Table
            columns={columns}
            size="small"
            dataSource={this.props.config.selectedAtomicQueryValue.sheets[0].data}
            pagination={this.renderPagination(this.props.config)}
          /></div>);
```

and generated css
```
<style type="text/css">.s1287016723 .ant-table-tbody tr td {
.s1287016723 color: red}
</style>
```

the problem is here **.s1287016723** color: red}

**Comment by buildbreakdo** [comment]
Hi @samankhademi , thanks for opening this! Technically CSS does not require a semi-colon for the last property-value in a CSS declaration block, looks like the parser does not account for this corner case. 

Add a semicolon to the end of your css key-value pair and will work. Like so:

`.foo { color: red; } `

Hope to have a fix up soon.

**Comment by buildbreakdo** [comment]
d6e2880f63c0b40e3ea7e17eb55d204929de31f0

**Comment by samankhademi** [comment]
yes!!!!!!!!!!!!!!! thank you man
