### ISSUE TITLE
Single declaration doesn't work without semicolon

### ISSUE THREAD

**Issue by cqliu1** [buildbreakdo/style-it#30]
![jan-03-2019 10-33-15](https://user-images.githubusercontent.com/1697105/50652225-086b8380-0f43-11e9-842a-15cc33f48cce.gif)

It seems to only work when you add an additional space at the end.

**Comment by buildbreakdo** [comment]
@cqliu1 Thanks for opening this. Can you confirm the screenshot is from version 2.1.0? Have added a test case [here](https://github.com/buildbreakdo/style-it/commit/e1a99f82df1e035ecaea008cde979e7e889bb464) to reproduce and it is passing.

**Comment by cqliu1** [comment]
@buildbreakdo Yep, I'm using version 2.1.0. It might be an issue with our implementation. Let me take a look.

**Comment by cqliu1** [comment]
Btw this is the exact string being passed into `Style.it`: `".canvasPage {\n  color: red\n}"`

**Comment by buildbreakdo** [comment]
@cqliu1 Cool, thanks, I'll try that one and see if I can reproduce.

**Comment by buildbreakdo** [comment]
@cqliu1 Yes, that failed, thanks! Very interesting.. should have a fix in today. Thanks so much for opening this!

**Comment by cqliu1** [comment]
@buildbreakdo Great! Thanks so much!

**Comment by buildbreakdo** [comment]
@cqliu1 Okay this is fixed in 2.1.1, test to confirm is here: https://github.com/buildbreakdo/style-it/blob/master/__tests__/Style-24.js

Thanks for the assist with this!

**Comment by w33ble** [comment]
@buildbreakdo you rock!

Also, I just learned this and thought I'd share; `|[\n\t\s]+` is redundant, `\s` includes `\n` and `\t`, so all you need is `|[\s]+`. I changed it locally and the test still passes. No real need to change it, of course.

**Comment by buildbreakdo** [comment]
@w33ble Nice catch! Can drop the character class too after reducing to `|\s+`. Had `|[\n\t ]+` and never was fond of the space character in the middle of a regex (bit too camouflaged) and switched to `\s`. Redundancy removed in 2.1.2

**Comment by w33ble** [comment]
I just sent you a message using the email in your commit history.
