### ISSUE TITLE
Dependency react-lib-adler32 is missing license

### ISSUE THREAD

**Issue by peterschretlen** [buildbreakdo/style-it#33]
We've been using `style-it` in the [canvas](https://www.elastic.co/guide/en/kibana/current/canvas.html) feature in Kibana, but it was flagged during an open source license audit because of a dependency on `react-lib-adler32`.

https://github.com/buildbreakdo/style-it/blob/master/package.json#L129

The `react-lib-adler32` dependency was flagged as having no license file.  From the source it appears to be a redistribution of code that was under a BSD 3-clause license, but it doesn't include a BSD license itself. 

Since Kibana builds include all the dependencies including transitive ones, we're looking at ways to either correct `react-lib-adler32` or work around it so we can continue using `style-it`. 

I wanted to see if it would be possible to either:
- update react-lib-adler32 ( @buildbreakdo it appears you are the author ?) to add the BSD-3 clause license. 
- Have style-it vendor in the [adler32 code](https://unpkg.com/react-lib-adler32@1.0.1/adler32.js), carrying forward the required information to satisfy the terms of the BSD-3 clause license.

**Comment by buildbreakdo** [comment]
Hi @peterschretlen, very interesting, thanks for reaching out. License for `react-lib-adler32` is mentioned at the top of the source code. Turned one of Facebooks utilities into a module after being told by the Facebook team that the public should not expect any source code stability from their internally consumed libraries, `react-lib-adler32` was the quick solution (3 years ago).

Quote from top of the source code:

```
/**
 * Copyright 2013-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * @providesModule adler32
 */
```

Link to their most current license file can be found below, Facebook (quite publicly) switched from BSD-style to MIT License which can be found here:
https://github.com/facebook/react/blob/master/LICENSE

Not sure what the next steps would be. Although I will say, that if Kibana legal team has approved React then that library is under the same license and is also approved?

**Comment by buildbreakdo** [comment]
Here is a link to Facebooks announcement:

https://code.fb.com/web/relicensing-react-jest-flow-and-immutable-js/

**Comment by peterschretlen** [comment]
@buildbreakdo yeah I hate to even raise this as it seems pedantic.  But we take care to respect the code we use and its authors, so I hope you'll bear with me 😄 

As-is `react-lib-adler32` gets classified by our open source policy as unlicensed code, which prevents us from using it.  While a  BSD-style license and patent file are mentioned, they're not included or referenced (for example with a URL). 

You're right, the react v16.0 version of the code is MIT licensed (the code seems to be gone in master): 
https://github.com/facebook/react/blob/5c6ef4044610a2a325780261f41730a33a919f98/src/renderers/shared/utils/adler32.js

So if the package was updated to include this text in the source header:
https://github.com/facebook/react/blob/5c6ef4044610a2a325780261f41730a33a919f98/LICENSE
Then I think we'd be good. 

I think there's 3 possible next steps:
1) update the `react-lib-adler32` source header to use the [MIT license header and facebook copyright](https://github.com/facebook/react/blob/5c6ef4044610a2a325780261f41730a33a919f98/LICENSE)
2) include the source in `style-it` with the same header. Sometimes a NOTICE.txt is included as well -  ([here](https://github.com/elastic/kibana/blob/master/NOTICE.txt) is Kibana's for example) 
3) do nothing.  Kibana could fork `style-it` or vendor the code to keep using it. It's not ideal but Kibana could take on making the changes and then make a PR - we are the ones raising it after all 😄. 

Any of these are fine, though I'm hoping we could just update to v2.1.3!

**Comment by peterschretlen** [comment]
@buildbreakdo I see 2.1.3 was just released - thank you for doing that!  closing the issue
